server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://oeong.com:3306/farm_produce?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: farm_produce
    password: jLJ2sCGkyYKYzKnd

#mybatis:
#  mapper-locations:
#    - classpath:mapper/*.xml
#    - classpath*:com/**/mapper/*.xml
