server:
  port: 8088
spring:
  application:
    name: system
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #navicat连接，记不住ip可以直接用域名，项目里面直接用ip加快访问
    url: jdbc:mysql://139.224.164.169/traceap?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: tracer
    password: Aa111111
    hikari:
      max-lifetime: 120000
  jackson:
    time-zone: Asia/Shanghai
    # Date返回前端转时间戳 但不能解决LocalDateTime转时间戳（JacksonCustomizerConfig类解决）
    serialization:
      write-dates-as-timestamps: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
