spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: system
          uri: lb://system
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
#            - name: RequestRateLimiter #一秒10次请求
#              args:
#                key-resolver: "#{@ipKeyResolver}"
#                redis-rate-limiter:
#                  replenishRate: 10 #每次补充令牌数量
#                  burstCapacity: 10 #令牌桶最大容量，突发请求数量
#                  requestedTokens: 1 #每次请求消耗令牌的数量
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 300000
        read-timeout: 300000