spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      routes:
        - id: oauth
          uri: lb://oauth
          predicates:
            - Path=/api/oauth/login
          filters:
            - StripPrefix=1
        - id: web
          uri: lb://web
          predicates:
            - Path=/wf/assets/src/**
          filters:
            - StripPrefix=3
        - id: web
          uri: lb://web
          predicates:
            - Path=/wf/src/**
          filters:
            - StripPrefix=2
        - id: web
          uri: lb://web
          predicates:
            - Path=/wf,/wf/**
          filters:
            - StripPrefix=1
        - id: system
          uri: lb://system
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
        - id: system
          uri: lb://system
          predicates:
            - Path=/wf/api/**
          filters:
            - StripPrefix=2
        - id: web
          uri: lb://web
          predicates:
            - Path=/assets/**
#            - name: RequestRateLimiter #一秒10次请求
#              args:
#                key-resolver: "#{@ipKeyResolver}"
#                redis-rate-limiter:
#                  replenishRate: 10 #每次补充令牌数量
#                  burstCapacity: 10 #令牌桶最大容量，突发请求数量
#                  requestedTokens: 1 #每次请求消耗令牌的数量
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true