server:
  port: 9001
spring:
  application:
    name: oauth
  mvc:
    static-path-pattern: /**
    view:
      prefix: classpath:resources/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://139.224.164.169:3306/traceap?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: tracer
    password: Aa111111
  main:
    allow-bean-definition-overriding: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
auth:
  ttl: 3600  #token存储到cookie的过期时间
  clientId: test
  clientSecret: 123456
  cookieDomain: lqjai.com
  cookieMaxAge: -1
encrypt:
  key-store:
    location: classpath:/qjmall.jks
    secret: qjmall
    alias: qjmall
    password: qjmall